[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore:.*Eventlet is deprecated.*:DeprecationWarning
    ignore::DeprecationWarning:zstandard
    ignore::DeprecationWarning:msgpack
    ignore:.*win32api.*:UserWarning
    ignore:.*Unverified HTTPS.*:UserWarning
